// Generated by Selenium IDE
package roundTrip;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SelectingFlightTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void selectingFlight() {
    driver.get("https://www.makemytrip.com/");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.cssSelector(".loginModal")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > .tabsCircle")).click();
    driver.findElement(By.id("fromCity")).click();
    driver.findElement(By.cssSelector(".react-autosuggest__input")).click();
    driver.findElement(By.cssSelector(".react-autosuggest__input")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector(".react-autosuggest__input")).sendKeys("Chennai");
    driver.findElement(By.cssSelector(".react-autosuggest__input")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.id("toCity"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-autosuggest__input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".searchToCity")).click();
    driver.findElement(By.cssSelector(".react-autosuggest__input")).click();
    driver.findElement(By.cssSelector(".react-autosuggest__input")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector(".react-autosuggest__input")).sendKeys("New Delhi");
    driver.findElement(By.cssSelector(".react-autosuggest__input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".DayPicker-Day--end > .dateInnerCell")).click();
    driver.findElement(By.cssSelector(".fsw_inputBox:nth-child(4) .lbl_input")).click();
    driver.findElement(By.cssSelector(".DayPicker-Month:nth-child(1) .DayPicker-Week:nth-child(4) > .DayPicker-Day:nth-child(7) p")).click();
    driver.findElement(By.cssSelector(".DayPicker-Day--selected:nth-child(3) p:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".blackText > .appendRight10")).click();
    driver.findElement(By.cssSelector(".childCounter li:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".flightTravllers .lbl_input")).click();
    driver.findElement(By.cssSelector(".btnApply")).click();
    driver.findElement(By.cssSelector(".primaryBtn")).click();
    driver.findElement(By.cssSelector(".filtersOuter:nth-child(1) .filtersOuter > div > .makeFlex:nth-child(4) .box")).click();
    driver.findElement(By.cssSelector("#flightCard-17 .outer")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > #flightCard-7000 .outer")).click();
    driver.findElement(By.id("bookbutton-RKEY:77f9f990-c125-4e3b-9e19-a36c2032604c:19_0~~~RKEY:77f9f990-c125-4e3b-9e19-a36c2032604c:36_0")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".multifareFooter > #bookbutton-RKEY\\3A 77f9f990-c125-4e3b-9e19-a36c2032604c\\3A 19_0\\~\\~\\~RKEY\\3A 77f9f990-c125-4e3b-9e19-a36c2032604c\\3A 36_0")).click();
    vars.put("win9369", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9369").toString());
  }
}
